name: Windows - Anydesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Archive project content
      uses: actions/upload-artifact@v2
  
    - name: Downloading & Installing Essentials
      run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/anydesk-windows-rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

    - name: Log In To AnyDesk
      run: cmd /c start.bat

    - name: Time Counter
      run: python time.py
